import os
import json
from typing import Dict, List, Any, Optional, Tuple

# openpyxl imports
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side
from openpyxl.utils import get_column_letter

# reportlab imports
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    """Custom canvas implementation to add headers and footers with accurate page counts."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []
        self.load_business_settings()

    def load_business_settings(self):
        """Loads business configurations dynamically from settings.json."""
        self.biz_name = "Jalaj Ledger"
        self.owner_name = "Jalaj Singhal"
        self.phone = "+91XXXXXXXXXX"
        self.address = "Business Address"
        
        if os.path.exists("settings.json"):
            try:
                with open("settings.json", "r") as f:
                    data = json.load(f)
                    self.biz_name = data.get("name") or data.get("business_name") or "Jalaj Ledger"
                    self.owner_name = data.get("owner_name") or "Jalaj Singhal"
                    self.phone = data.get("business_phone") or data.get("phone") or "+91XXXXXXXXXX"
                    self.address = data.get("address") or "Business Address"
            except Exception as e:
                print(f"Error loading settings in NumberedCanvas: {e}")

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        
        # 1. Running Header
        self.setFont("Helvetica-Bold", 11)
        self.setFillColor(colors.HexColor("#0F172A"))  # Slate 900
        self.drawString(54, 760, self.biz_name.upper())
        
        self.setFont("Helvetica", 8.5)
        self.setFillColor(colors.HexColor("#64748B"))  # Slate 500
        self.drawString(54, 746, f"Owner: {self.owner_name}")
        self.drawString(54, 734, f"Phone: {self.phone}")
        self.drawString(54, 722, f"Address: {self.address}")
        
        # Separator line
        self.setStrokeColor(colors.HexColor("#E2E8F0"))  # Slate 200
        self.setLineWidth(1)
        self.line(54, 712, 558, 712)
        
        # 2. Running Footer
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(54, 55, 558, 55)
        
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#94A3B8"))  # Slate 400
        self.drawString(54, 42, f"{self.biz_name} | Phone: {self.phone}")
        self.drawString(54, 30, "Generated by Ledger Management System")
        
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 42, page_text)
        
        self.restoreState()


class ExportService:
    """Generates premium quality styled PDF and Excel files using ReportLab and OpenPyXL."""

    def __init__(self):
        pass

    # ------------------------------------------------------------------ #
    #  Private: PDF Encryption Hook
    # ------------------------------------------------------------------ #

    @staticmethod
    def _apply_pdf_encryption(pdf_path: str) -> Tuple[bool, str]:
        """
        Post-processes a generated PDF with password encryption if security is
        enabled in settings.json.  Called after every doc.build() invocation.

        Behaviour:
          - If PDF security is disabled (or no password configured) → no-op, returns (True, "").
          - On successful encryption → original file is replaced atomically.
          - On any error → unencrypted file is left intact, error is logged.
          - Application never crashes from encryption failures.

        Returns:
            (True,  "")          — encrypted successfully, or security disabled
            (False, reason_str)  — encryption attempted but failed
        """
        try:
            from ledger_app.services.pdf_security_service import PdfSecurityService
            svc = PdfSecurityService()

            if not svc.is_security_enabled():
                return True, ""

            ph, salt = svc.get_active_password_hash_and_salt()
            if not ph or not salt:
                return True, ""  # Security enabled but no password set yet

            # We cannot recover the plaintext password from the hash.
            # The encrypt_pdf call requires the raw password, so we store
            # a temporary plaintext copy ONLY in memory at the time the
            # user sets/changes it.  We retrieve it here from settings via
            # a one-time decryption-bypass: instead we store the *hashed*
            # password for verification and separately store the *encryption*
            # key material differently.
            #
            # DESIGN NOTE:
            # PDF encryption requires the raw password at export time.  Since
            # we cannot reconstruct the raw password from PBKDF2, we keep a
            # separate AES-key-equivalent in settings: the 'pdf_user_key' field
            # which stores the raw password XOR-obfuscated with its own salt.
            # This is NOT meant to be cryptographic secrecy of the key at rest
            # (the settings file is local) — it is meant to prevent casual
            # shoulder-surfing and trivial plaintext exposure.
            #
            # For true key-at-rest security, an OS keychain integration would
            # be used.  For a desktop ledger app this level is appropriate.
            settings_data = svc._load_settings()
            pdf_user_key = settings_data.get("pdf_user_key", "")
            if not pdf_user_key:
                print("[PdfSecurity] Warning: pdf_user_key missing — cannot encrypt PDF.")
                return True, ""

            # XOR-deobfuscate the raw password
            raw_password = PdfSecurityService.deobfuscate_key(pdf_user_key, salt)

            ok, err = PdfSecurityService.encrypt_pdf(pdf_path, pdf_path, raw_password)
            if not ok:
                print(f"[PdfSecurity] Encryption failed for '{pdf_path}': {err}")
                return False, err

            print(f"[PdfSecurity] PDF encrypted successfully: {pdf_path}")
            return True, ""

        except Exception as e:
            print(f"[PdfSecurity] Unexpected error during PDF encryption: {e}")
            return False, str(e)

    def export_ledger_to_excel(self, ledger_data: Dict[str, Any], output_path: str) -> None:
        """Exports a customer ledger statement to a formatted Excel file."""
        wb = Workbook()
        ws = wb.active
        ws.title = "Ledger Statement"
        ws.views.sheetView[0].showGridLines = True

        customer = ledger_data["customer"]

        # Color Fills
        navy_fill = PatternFill(start_color="2E4A62", end_color="2E4A62", fill_type="solid")
        light_gray_fill = PatternFill(start_color="F7F9FB", end_color="F7F9FB", fill_type="solid")
        kpi_fill = PatternFill(start_color="EAF2F8", end_color="EAF2F8", fill_type="solid")

        # Fonts
        title_font = Font(name="Segoe UI", size=16, bold=True, color="FFFFFF")
        header_font = Font(name="Segoe UI", size=11, bold=True, color="FFFFFF")
        regular_font = Font(name="Segoe UI", size=10)
        bold_font = Font(name="Segoe UI", size=10, bold=True)

        # Borders
        thin_side = Side(border_style="thin", color="CCCCCC")
        thick_bottom_side = Side(border_style="double", color="333333")
        border_all = Border(left=thin_side, right=thin_side, top=thin_side, bottom=thin_side)
        border_total = Border(top=thin_side, bottom=thick_bottom_side)

        # Alignments
        align_left = Alignment(horizontal="left", vertical="center")
        align_right = Alignment(horizontal="right", vertical="center")
        align_center = Alignment(horizontal="center", vertical="center")

        # Title Block
        ws.merge_cells("A1:G2")
        title_cell = ws["A1"]
        title_cell.value = "CUSTOMER LEDGER STATEMENT"
        title_cell.font = title_font
        title_cell.fill = navy_fill
        title_cell.alignment = align_center

        # Customer Metadata Block
        ws["A4"] = "Customer Name:"
        ws["A4"].font = bold_font
        ws["B4"] = customer.name
        ws["B4"].font = regular_font

        ws["A5"] = "Phone Number:"
        ws["A5"].font = bold_font
        ws["B5"] = customer.phone or "N/A"
        ws["B5"].font = regular_font

        ws["A6"] = "Address:"
        ws["A6"].font = bold_font
        ws["B6"] = customer.address or "N/A"
        ws["B6"].font = regular_font

        # Summary Metrics KPI Card Block
        ws.merge_cells("E4:G4")
        ws["E4"] = "Statement Summary"
        ws["E4"].font = Font(name="Segoe UI", size=11, bold=True, color="1B4F72")
        ws["E4"].alignment = align_center
        ws["E4"].fill = kpi_fill

        ws["E5"] = "Opening Balance:"
        ws["E5"].font = regular_font
        ws["G5"] = ledger_data["opening_balance"]
        ws["G5"].font = bold_font
        ws["G5"].number_format = "$#,##0.00"
        ws["G5"].alignment = align_right

        ws["E6"] = "Total Debits:"
        ws["E6"].font = regular_font
        ws["G6"] = ledger_data["total_debits"]
        ws["G6"].font = bold_font
        ws["G6"].number_format = "$#,##0.00"
        ws["G6"].alignment = align_right

        ws["E7"] = "Total Credits:"
        ws["E7"].font = regular_font
        ws["G7"] = ledger_data["total_credits"]
        ws["G7"].font = bold_font
        ws["G7"].number_format = "$#,##0.00"
        ws["G7"].alignment = align_right

        ws["E8"] = "Outstanding Balance:"
        ws["E8"].font = bold_font
        ws["G8"] = ledger_data["current_balance"]
        ws["G8"].font = Font(name="Segoe UI", size=10, bold=True, color="C0392B" if ledger_data["current_balance"] > 0 else "27AE60")
        ws["G8"].number_format = "$#,##0.00"
        ws["G8"].alignment = align_right

        # Table Headers
        headers = ["Txn ID", "Date & Time", "Description", "Payment Mode", "Debit (Charge)", "Credit (Payment)", "Running Balance"]
        start_row = 10
        for col_idx, header in enumerate(headers, 1):
            cell = ws.cell(row=start_row, column=col_idx)
            cell.value = header
            cell.font = header_font
            cell.fill = navy_fill
            cell.alignment = align_center
            cell.border = border_all

        # Table Rows
        current_row = start_row + 1
        for idx, txn in enumerate(ledger_data["transactions"], 1):
            ws.cell(row=current_row, column=1, value=txn["id"]).alignment = align_center
            ws.cell(row=current_row, column=2, value=txn["transaction_date"]).alignment = align_center
            ws.cell(row=current_row, column=3, value=txn["description"] or "-").alignment = align_left
            ws.cell(row=current_row, column=4, value=txn["mode_name"] or "-").alignment = align_center
            
            # Debit/Credit splitting
            is_debit = txn["transaction_type"] in ("DEBIT", "DAILY_CHARGE")
            debit_val = txn["amount"] if is_debit else 0.0
            credit_val = txn["amount"] if not is_debit else 0.0
            
            ws.cell(row=current_row, column=5, value=debit_val).number_format = "$#,##0.00"
            ws.cell(row=current_row, column=5).alignment = align_right
            ws.cell(row=current_row, column=6, value=credit_val).number_format = "$#,##0.00"
            ws.cell(row=current_row, column=6).alignment = align_right
            
            ws.cell(row=current_row, column=7, value=txn["running_balance"]).number_format = "$#,##0.00"
            ws.cell(row=current_row, column=7).alignment = align_right

            # Zebra striping
            fill = light_gray_fill if idx % 2 == 0 else PatternFill(fill_type=None)
            for c in range(1, 8):
                cell = ws.cell(row=current_row, column=c)
                if fill.fill_type:
                    cell.fill = fill
                cell.font = regular_font
                cell.border = border_all

            current_row += 1

        # Summary Total Row
        total_row = current_row
        ws.cell(row=total_row, column=3, value="Total Summaries").font = bold_font
        ws.cell(row=total_row, column=5, value=f"=SUM(E{start_row+1}:E{total_row-1})").number_format = "$#,##0.00"
        ws.cell(row=total_row, column=5).alignment = align_right
        ws.cell(row=total_row, column=5).font = bold_font
        
        ws.cell(row=total_row, column=6, value=f"=SUM(F{start_row+1}:F{total_row-1})").number_format = "$#,##0.00"
        ws.cell(row=total_row, column=6).alignment = align_right
        ws.cell(row=total_row, column=6).font = bold_font

        for c in range(1, 8):
            ws.cell(row=total_row, column=c).border = border_total

        # Auto-adjust column widths
        for col in ws.columns:
            max_len = 0
            col_letter = get_column_letter(col[0].column)
            for cell in col:
                val_str = str(cell.value or '')
                if cell.row in (1, 2) and col_letter != 'A':
                    continue
                if len(val_str) > max_len:
                    max_len = len(val_str)
            ws.column_dimensions[col_letter].width = max(max_len + 3, 12)

        wb.save(output_path)


    def export_ledger_to_pdf(self, ledger_data: Dict[str, Any], output_path: str, 
                            business_info: Optional[Dict[str, str]] = None) -> None:
        """Exports a customer ledger statement to a professional PDF document."""
        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)

        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            rightMargin=54,
            leftMargin=54,
            topMargin=115,
            bottomMargin=75
        )
        
        styles = getSampleStyleSheet()
        
        title_style = ParagraphStyle(
            'DocTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=16,
            textColor=colors.HexColor('#0F172A'),
            spaceAfter=10
        )
        meta_label_style = ParagraphStyle(
            'MetaLabel',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=9.5,
            textColor=colors.HexColor('#334155')
        )
        meta_val_style = ParagraphStyle(
            'MetaVal',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9.5,
            textColor=colors.HexColor('#475569')
        )
        table_header_style = ParagraphStyle(
            'TableHeader',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=9,
            textColor=colors.white,
            alignment=1
        )
        table_cell_style = ParagraphStyle(
            'TableCell',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=8,
            textColor=colors.HexColor('#334155')
        )
        table_cell_center = ParagraphStyle(
            'TableCellCenter',
            parent=table_cell_style,
            alignment=1
        )
        table_cell_right = ParagraphStyle(
            'TableCellRight',
            parent=table_cell_style,
            alignment=2
        )

        story = []

        # Document Header Title & Divider
        story.append(Paragraph("CUSTOMER LEDGER STATEMENT", title_style))
        
        hr = Table([[""]], colWidths=[504])
        hr.setStyle(TableStyle([
            ('LINEABOVE', (0, 0), (-1, -1), 1, colors.HexColor("#E2E8F0")),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
            ('TOPPADDING', (0, 0), (-1, -1), 0),
        ]))
        story.append(hr)
        story.append(Spacer(1, 15))

        # Metadata side-by-side card panels
        customer = ledger_data["customer"]
        b_name = business_info.get("name", "Ledger Management System") if business_info else "My Business"
        b_owner = business_info.get("owner_name", "") if business_info else ""
        b_phone = business_info.get("phone", "") if business_info else ""
        b_addr = business_info.get("address", "") if business_info else ""

        meta_data = [
            [Paragraph("Customer Details", meta_label_style), "", Paragraph("Business Information", meta_label_style), ""],
            [Paragraph("Name:", meta_label_style), Paragraph(customer.name, meta_val_style), 
             Paragraph("Company:", meta_label_style), Paragraph(b_name, meta_val_style)],
            [Paragraph("Phone:", meta_label_style), Paragraph(customer.phone or "N/A", meta_val_style), 
             Paragraph("Owner:", meta_label_style), Paragraph(b_owner or "N/A", meta_val_style)],
            [Paragraph("Address:", meta_label_style), Paragraph(customer.address or "N/A", meta_val_style), 
             Paragraph("Phone:", meta_label_style), Paragraph(b_phone or "N/A", meta_val_style)],
            ["", "", Paragraph("Address:", meta_label_style), Paragraph(b_addr or "N/A", meta_val_style)]
        ]

        meta_table = Table(meta_data, colWidths=[60, 182, 60, 202])
        meta_table.setStyle(TableStyle([
            ('SPAN', (0, 0), (1, 0)),
            ('SPAN', (2, 0), (3, 0)),
            ('BACKGROUND', (0, 0), (1, 0), colors.HexColor("#F1F5F9")),
            ('BACKGROUND', (2, 0), (3, 0), colors.HexColor("#F1F5F9")),
            ('LINEBELOW', (0, 0), (1, 0), 1, colors.HexColor("#CBD5E1")),
            ('LINEBELOW', (2, 0), (3, 0), 1, colors.HexColor("#CBD5E1")),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('BOX', (0, 0), (1, -1), 1, colors.HexColor("#E2E8F0")),
            ('BOX', (2, 0), (3, -1), 1, colors.HexColor("#E2E8F0")),
        ]))
        
        story.append(meta_table)
        story.append(Spacer(1, 20))

        # Table headers and rows
        table_data = [
            [
                Paragraph("Date", table_header_style),
                Paragraph("Description", table_header_style),
                Paragraph("Payment Mode", table_header_style),
                Paragraph("Debit (+)", table_header_style),
                Paragraph("Credit (-)", table_header_style),
                Paragraph("Balance", table_header_style)
            ]
        ]

        for txn in ledger_data["transactions"]:
            is_debit = txn["transaction_type"] in ("DEBIT", "DAILY_CHARGE")
            debit_str = f"${txn['amount']:,.2f}" if is_debit else "-"
            debit_color = "#EF4444" if is_debit else "#334155"
            
            credit_str = f"${txn['amount']:,.2f}" if not is_debit else "-"
            credit_color = "#22C55E" if not is_debit else "#334155"
            
            bal = txn["running_balance"]
            bal_color = "#EF4444" if bal > 0 else ("#22C55E" if bal < 0 else "#334155")
            bal_str = f"-${abs(bal):,.2f}" if bal < 0 else f"${bal:,.2f}"
            
            debit_style = ParagraphStyle('DebLed', parent=table_cell_right, fontName='Helvetica-Bold' if is_debit else 'Helvetica', textColor=colors.HexColor(debit_color))
            credit_style = ParagraphStyle('CredLed', parent=table_cell_right, fontName='Helvetica-Bold' if not is_debit else 'Helvetica', textColor=colors.HexColor(credit_color))
            bal_style = ParagraphStyle('BalLed', parent=table_cell_right, fontName='Helvetica-Bold', textColor=colors.HexColor(bal_color))

            table_data.append([
                Paragraph(txn["transaction_date"][:16] if txn["transaction_date"] else "-", table_cell_center),
                Paragraph(txn["description"] or "-", table_cell_style),
                Paragraph(txn["mode_name"] or "-", table_cell_center),
                Paragraph(debit_str, debit_style),
                Paragraph(credit_str, credit_style),
                Paragraph(bal_str, bal_style)
            ])

        # Totals summaries
        curr_bal = ledger_data['current_balance']
        curr_bal_str = f"-${abs(curr_bal):,.2f}" if curr_bal < 0 else f"${curr_bal:,.2f}"
        table_data.append([
            Paragraph("<b>Total Summaries</b>", table_cell_style), "", "",
            Paragraph(f"<b>${ledger_data['total_debits']:,.2f}</b>", table_cell_right),
            Paragraph(f"<b>${ledger_data['total_credits']:,.2f}</b>", table_cell_right),
            Paragraph(f"<b>{curr_bal_str}</b>", table_cell_right)
        ])

        txn_table = Table(table_data, colWidths=[80, 144, 75, 65, 65, 75])
        
        t_style = TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#0F172A")),
            ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('GRID', (0, 0), (-1, -2), 0.5, colors.HexColor("#E2E8F0")),
            ('LINEABOVE', (0, -1), (-1, -1), 1.5, colors.HexColor("#0F172A")),
            ('SPAN', (0, -1), (2, -1)),
        ])

        # Zebra striping
        for idx in range(1, len(ledger_data["transactions"]) + 1):
            if idx % 2 == 0:
                t_style.add('BACKGROUND', (0, idx), (-1, idx), colors.HexColor("#F8FAFC"))

        txn_table.setStyle(t_style)
        story.append(txn_table)

        doc.build(story, canvasmaker=NumberedCanvas)
        self._apply_pdf_encryption(output_path)


    def export_report_to_excel(self, report_title: str, headers: List[str], 
                               data_rows: List[List[Any]], output_path: str) -> None:
        """Exports generic report results table to a premium styled Excel spreadsheet."""
        wb = Workbook()
        ws = wb.active
        ws.title = "Report"
        ws.views.sheetView[0].showGridLines = True

        # Styles
        navy_fill = PatternFill(start_color="2E4A62", end_color="2E4A62", fill_type="solid")
        light_gray_fill = PatternFill(start_color="F7F9FB", end_color="F7F9FB", fill_type="solid")
        
        title_font = Font(name="Segoe UI", size=15, bold=True, color="FFFFFF")
        header_font = Font(name="Segoe UI", size=11, bold=True, color="FFFFFF")
        regular_font = Font(name="Segoe UI", size=10)
        bold_font = Font(name="Segoe UI", size=10, bold=True)
        
        thin_side = Side(border_style="thin", color="CCCCCC")
        border_all = Border(left=thin_side, right=thin_side, top=thin_side, bottom=thin_side)

        align_center = Alignment(horizontal="center", vertical="center")
        align_left = Alignment(horizontal="left", vertical="center")
        align_right = Alignment(horizontal="right", vertical="center")

        # Title
        num_cols = len(headers)
        col_end_letter = get_column_letter(num_cols)
        ws.merge_cells(f"A1:{col_end_letter}2")
        title_cell = ws["A1"]
        title_cell.value = report_title.upper()
        title_cell.font = title_font
        title_cell.fill = navy_fill
        title_cell.alignment = align_center

        # Headers
        start_row = 4
        for col_idx, header in enumerate(headers, 1):
            cell = ws.cell(row=start_row, column=col_idx)
            cell.value = header
            cell.font = header_font
            cell.fill = navy_fill
            cell.alignment = align_center
            cell.border = border_all

        # Data Rows
        current_row = start_row + 1
        for row_idx, row_data in enumerate(data_rows, 1):
            for col_idx, val in enumerate(row_data, 1):
                cell = ws.cell(row=current_row, column=col_idx, value=val)
                
                # Format cell based on data types
                if isinstance(val, float):
                    cell.number_format = "$#,##0.00"
                    cell.alignment = align_right
                elif isinstance(val, int) and col_idx == 1:
                    cell.alignment = align_center
                elif "date" in headers[col_idx-1].lower() or "time" in headers[col_idx-1].lower():
                    cell.alignment = align_center
                else:
                    cell.alignment = align_left
                
                # Zebra colors
                if row_idx % 2 == 0:
                    cell.fill = light_gray_fill
                cell.font = regular_font
                cell.border = border_all
            current_row += 1

        # Adjust width dynamically
        for col in ws.columns:
            max_len = 0
            col_letter = get_column_letter(col[0].column)
            for cell in col:
                val_str = str(cell.value or '')
                if cell.row in (1, 2) and col_letter != 'A':
                    continue
                if len(val_str) > max_len:
                    max_len = len(val_str)
            ws.column_dimensions[col_letter].width = max(max_len + 3, 12)

        wb.save(output_path)


    def export_report_to_pdf(self, report_title: str, headers: List[str], 
                            data_rows: List[List[Any]], output_path: str,
                            business_info: Optional[Dict[str, str]] = None) -> None:
        """Exports a generic tabular report to a formatted, printable PDF document."""
        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        
        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            rightMargin=54,
            leftMargin=54,
            topMargin=115,
            bottomMargin=75
        )
        
        styles = getSampleStyleSheet()
        
        title_style = ParagraphStyle(
            'ReportTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=16,
            textColor=colors.HexColor('#0F172A'),
            spaceAfter=10
        )
        header_style = ParagraphStyle(
            'ReportHeaderCol',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=9,
            textColor=colors.white,
            alignment=1
        )
        cell_style = ParagraphStyle(
            'ReportCellCol',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=8.5,
            textColor=colors.HexColor('#334155')
        )
        cell_center = ParagraphStyle('ReportCellCenter', parent=cell_style, alignment=1)
        cell_right = ParagraphStyle('ReportCellRight', parent=cell_style, alignment=2)

        story = []

        # Report Title
        story.append(Paragraph(report_title, title_style))
        
        # Divider line
        hr = Table([[""]], colWidths=[504])
        hr.setStyle(TableStyle([
            ('LINEABOVE', (0, 0), (-1, -1), 1, colors.HexColor("#E2E8F0")),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
            ('TOPPADDING', (0, 0), (-1, -1), 0),
        ]))
        story.append(hr)
        story.append(Spacer(1, 15))

        # Build table rows
        table_data = [
            [Paragraph(h, header_style) for h in headers]
        ]

        for row in data_rows:
            formatted_row = []
            for col_idx, val in enumerate(row):
                header_name = headers[col_idx].lower()
                
                # Check formatting
                if isinstance(val, float):
                    if "balance" in header_name or "net" in header_name:
                        color = "#EF4444" if val > 0 else ("#22C55E" if val < 0 else "#334155")
                    else:
                        color = "#334155"
                    val_str = f"-${abs(val):,.2f}" if val < 0 else f"${val:,.2f}"
                    style_r = ParagraphStyle('RepR', parent=cell_right, textColor=colors.HexColor(color), fontName='Helvetica-Bold')
                    cell_p = Paragraph(val_str, style_r)
                elif "date" in header_name or "time" in header_name or col_idx == 0:
                    cell_p = Paragraph(str(val), cell_center)
                else:
                    cell_p = Paragraph(str(val), cell_style)
                formatted_row.append(cell_p)
            table_data.append(formatted_row)

        total_width = 504.0
        col_width = total_width / len(headers)
        col_widths = [col_width] * len(headers)

        report_table = Table(table_data, colWidths=col_widths)
        
        t_style = TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#0F172A")),
            ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ])

        for idx in range(1, len(data_rows) + 1):
            if idx % 2 == 0:
                t_style.add('BACKGROUND', (0, idx), (-1, idx), colors.HexColor("#F8FAFC"))

        report_table.setStyle(t_style)
        story.append(report_table)

        doc.build(story, canvasmaker=NumberedCanvas)
        self._apply_pdf_encryption(output_path)


    def export_daily_summary_pdf(self, summary_data: Dict[str, Any], 
                                 todays_txns: List[Dict[str, Any]], output_path: str) -> None:
        """Generates a Daily Summary PDF report containing dashboard aggregates and transactions."""
        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)

        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            rightMargin=54,
            leftMargin=54,
            topMargin=115,
            bottomMargin=75
        )
        
        styles = getSampleStyleSheet()
        
        # Styles configuration
        title_style = ParagraphStyle(
            'SummaryTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=16,
            textColor=colors.HexColor('#0F172A'),
            spaceAfter=10
        )
        meta_label_style = ParagraphStyle(
            'MetaLabel',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=9.5,
            textColor=colors.HexColor('#334155')
        )
        meta_val_style = ParagraphStyle(
            'MetaVal',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9.5,
            textColor=colors.HexColor('#475569')
        )
        table_header_style = ParagraphStyle(
            'TableHeader',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=9,
            textColor=colors.white,
            alignment=1
        )
        table_cell_style = ParagraphStyle(
            'TableCell',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=8.5,
            textColor=colors.HexColor('#334155')
        )
        table_cell_center = ParagraphStyle(
            'TableCellCenter',
            parent=table_cell_style,
            alignment=1
        )
        table_cell_right = ParagraphStyle(
            'TableCellRight',
            parent=table_cell_style,
            alignment=2
        )

        story = []

        # Document Title Block & Separator Line
        story.append(Paragraph("Daily Summary Report", title_style))
        
        hr = Table([[""]], colWidths=[504])
        hr.setStyle(TableStyle([
            ('LINEABOVE', (0, 0), (-1, -1), 1, colors.HexColor("#E2E8F0")),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
            ('TOPPADDING', (0, 0), (-1, -1), 0),
        ]))
        story.append(hr)
        story.append(Spacer(1, 15))

        # KPI Summaries Block (6 styled cards: Row 1 = Metadata, Row 2 = Financials)
        kpi_title_slate = ParagraphStyle('KPISlateT', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=8, textColor=colors.HexColor('#475569'), alignment=1)
        kpi_val_slate = ParagraphStyle('KPISlateV', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=14, textColor=colors.HexColor('#0F172A'), alignment=1)
        
        kpi_title_cust = ParagraphStyle('KPICustT', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=8, textColor=colors.HexColor('#0369A1'), alignment=1)
        kpi_val_cust = ParagraphStyle('KPICustV', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=14, textColor=colors.HexColor('#0369A1'), alignment=1)
        
        kpi_title_debit = ParagraphStyle('KPIDebitT', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=8, textColor=colors.HexColor('#B91C1C'), alignment=1)
        kpi_val_debit = ParagraphStyle('KPIDebitV', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=14, textColor=colors.HexColor('#B91C1C'), alignment=1)
        
        kpi_title_credit = ParagraphStyle('KPICreditT', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=8, textColor=colors.HexColor('#15803D'), alignment=1)
        kpi_val_credit = ParagraphStyle('KPICreditV', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=14, textColor=colors.HexColor('#15803D'), alignment=1)
        
        # Outstanding Balance style depends on value
        outstanding_val = summary_data.get('outstanding_balance', 0.0)
        if outstanding_val < 0:
            out_val_str = f"-${abs(outstanding_val):,.2f}"
            out_bg = colors.HexColor("#FEF2F2")
            out_border = colors.HexColor("#FEE2E2")
            out_text_color = colors.HexColor("#B91C1C")
        else:
            out_val_str = f"${outstanding_val:,.2f}"
            out_bg = colors.HexColor("#FFF7ED")
            out_border = colors.HexColor("#FFEDD5")
            out_text_color = colors.HexColor("#C2410C")
            
        kpi_title_out = ParagraphStyle('KPIOutT', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=8, textColor=out_text_color, alignment=1)
        kpi_val_out = ParagraphStyle('KPIOutV', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=14, textColor=out_text_color, alignment=1)

        kpi_data = [
            [
                Paragraph("REPORT DATE", kpi_title_slate),
                "",
                Paragraph("CLOSE TIME", kpi_title_slate),
                "",
                Paragraph("TOTAL CUSTOMERS", kpi_title_cust)
            ],
            [
                Paragraph(str(summary_data["date"]), kpi_val_slate),
                "",
                Paragraph(str(summary_data["time"]), kpi_val_slate),
                "",
                Paragraph(str(summary_data["customer_count"]), kpi_val_cust)
            ],
            [
                "", "", "", "", ""
            ],
            [
                Paragraph("TODAY'S DEBIT", kpi_title_debit),
                "",
                Paragraph("TODAY'S CREDIT", kpi_title_credit),
                "",
                Paragraph("OUTSTANDING BALANCE", kpi_title_out)
            ],
            [
                Paragraph(f"${summary_data['total_debit']:,.2f}", kpi_val_debit),
                "",
                Paragraph(f"${summary_data['total_credit']:,.2f}", kpi_val_credit),
                "",
                Paragraph(out_val_str, kpi_val_out)
            ]
        ]
        
        kpi_table = Table(kpi_data, colWidths=[160, 12, 160, 12, 160], rowHeights=[None, None, 12, None, None])
        kpi_table.setStyle(TableStyle([
            # Row 1 Card 1 (Report Date) - Slate
            ('BACKGROUND', (0, 0), (0, 1), colors.HexColor("#F8FAFC")),
            ('BOX', (0, 0), (0, 1), 1, colors.HexColor("#E2E8F0")),

            # Row 1 Card 2 (Close Time) - Slate
            ('BACKGROUND', (2, 0), (2, 1), colors.HexColor("#F8FAFC")),
            ('BOX', (2, 0), (2, 1), 1, colors.HexColor("#E2E8F0")),

            # Row 1 Card 3 (Total Customers) - Blue
            ('BACKGROUND', (4, 0), (4, 1), colors.HexColor("#F0F9FF")),
            ('BOX', (4, 0), (4, 1), 1, colors.HexColor("#E0F2FE")),

            # Row 2 Card 1 (Today's Debit) - Red
            ('BACKGROUND', (0, 3), (0, 4), colors.HexColor("#FEF2F2")),
            ('BOX', (0, 3), (0, 4), 1, colors.HexColor("#FEE2E2")),

            # Row 2 Card 2 (Today's Credit) - Green
            ('BACKGROUND', (2, 3), (2, 4), colors.HexColor("#F0FDF4")),
            ('BOX', (2, 3), (2, 4), 1, colors.HexColor("#DCFCE7")),

            # Row 2 Card 3 (Outstanding Balance) - Orange or Red depending on sign
            ('BACKGROUND', (4, 3), (4, 4), out_bg),
            ('BOX', (4, 3), (4, 4), 1, out_border),

            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            
            # Padding for the card content rows (Rows 0, 1, 3, 4)
            ('TOPPADDING', (0, 0), (-1, 1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, 1), 6),
            ('TOPPADDING', (0, 3), (-1, 4), 6),
            ('BOTTOMPADDING', (0, 3), (-1, 4), 6),
            
            # Clear padding for spacer row (Row 2) and spacer columns (Col 1, Col 3)
            ('TOPPADDING', (0, 2), (-1, 2), 0),
            ('BOTTOMPADDING', (0, 2), (-1, 2), 0),
            ('LEFTPADDING', (1, 0), (1, -1), 0),
            ('RIGHTPADDING', (1, 0), (1, -1), 0),
            ('LEFTPADDING', (3, 0), (3, -1), 0),
            ('RIGHTPADDING', (3, 0), (3, -1), 0),
        ]))
        
        kpi_wrapper = Table([[kpi_table]], colWidths=[504])
        kpi_wrapper.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('LEFTPADDING', (0, 0), (-1, -1), 0),
            ('RIGHTPADDING', (0, 0), (-1, -1), 0),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 15),
        ]))
        story.append(kpi_wrapper)

        # Transactions log title
        story.append(Paragraph("TODAY'S TRANSACTIONS LOG", meta_label_style))
        story.append(Spacer(1, 10))

        # Transactions Table Grid (5 columns: Date, Customer, Type, Payment Mode, Amount)
        table_data = [
            [
                Paragraph("Date", table_header_style),
                Paragraph("Customer", table_header_style),
                Paragraph("Type", table_header_style),
                Paragraph("Payment Mode", table_header_style),
                Paragraph("Amount", table_header_style)
            ]
        ]

        for txn in todays_txns:
            txn_type = txn["transaction_type"]
            is_debit = txn_type in ("DEBIT", "DAILY_CHARGE")
            type_display = "Debit" if txn_type == "DEBIT" else ("Charge" if txn_type == "DAILY_CHARGE" else "Credit")
            type_color = "#EF4444" if is_debit else "#22C55E"
            
            type_style = ParagraphStyle(
                'TypeStyle', 
                parent=table_cell_center, 
                fontName='Helvetica-Bold',
                textColor=colors.HexColor(type_color)
            )
            
            amount_style = ParagraphStyle(
                'AmountStyle', 
                parent=table_cell_right, 
                fontName='Helvetica-Bold',
                textColor=colors.HexColor(type_color)
            )
            
            table_data.append([
                Paragraph(txn["transaction_date"][:16] if txn["transaction_date"] else "-", table_cell_center),
                Paragraph(txn["customer_name"], table_cell_style),
                Paragraph(type_display, type_style),
                Paragraph(txn["mode_name"] or "-", table_cell_center),
                Paragraph(f"${txn['amount']:,.2f}", amount_style)
            ])

        # Width sum must match print size = 504 pt
        txn_table = Table(table_data, colWidths=[110, 134, 80, 90, 90])
        
        t_style = TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#0F172A")),  # Slate 900
            ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ])

        # Zebra striping
        for idx in range(1, len(todays_txns) + 1):
            if idx % 2 == 0:
                t_style.add('BACKGROUND', (0, idx), (-1, idx), colors.HexColor("#F8FAFC"))

        txn_table.setStyle(t_style)
        
        if len(todays_txns) == 0:
            story.append(Paragraph("No transactions were logged today.", meta_val_style))
        else:
            story.append(txn_table)

        doc.build(story, canvasmaker=NumberedCanvas)
        self._apply_pdf_encryption(output_path)
